config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/privacy', to: 'static_pages#privacy'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	def hello
		render html: "hello, world!"
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def privacy
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Textop"
    if page_title.empty?
      base_title
    else
      base_title + " | "  + page_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
      <footer class="footer">
        <small>
          <%= link_to "Textop", root_path %>, the text outline project.
        </small>
        <nav>
          <ul>
            <li><%= link_to "Contact", contact_path %></li>
            <li><%= link_to "Privacy", privacy_path %></li>
          </ul>
        </nav>
      </footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <b><%= link_to "TEXTOP", root_path, id: "logo" %></b>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Login', signup_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_rails_default.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Textop</h1>
<p>Future home of the Textop help page.</p>

app/views/static_pages/contact.erb
<% provide(:title, 'Contact') %>
<h1>Contact Textop</h1>
<p>For everything Textop, contact Larry Sanger at larry >at< sanger.io.</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'The Text Outline Project') %>
<div class='center jumbotron'>
  <h1>Textop</h1>
  <p>Textop is coming soon!</p>
  <p><%= link_to "New account", signup_path, class: 'btn btn-lg btn-primary' %></p>
</div>

app/views/static_pages/privacy.html.erb
<% provide(:title, "Privacy") %>
<h1>Privacy Policy for Textop</h1>
<p>Privacy policy to come. Where your privacy is not demonstrated in and
  guaranteed by FOSS code, we will put legal constraints on ourselves with the
  policy. In short: we will not access your data, ever. We will encrypt
  everything on the server and in transit, so we will not <em>be able</em>
  to access your data.</p>

app/views/users/new.html.erb
<% provide(:title, 'Signup') %>
<h1>Sign up to Textop</h1>
<p>Coming soon.</p>
<p>A Textop account will allow you to edit the Textop outline, chunks, etc.</p>